const mapDBToModel = ({
    id,
    title,
    year,
    performer,
    genre,
    duration,
    name,
    album_id,
    song_id,
    playlist_id,
    user_id,
    username,
    password,
    fullname,
  }) => ({
    id,
    title,
    year,
    performer,
    genre,
    duration,
    name,
    albumId: album_id,
    songId: song_id,
    playlistId: playlist_id,
    userId: user_id,
    username,
    password,
    fullname,
  });
  
module.exports = { mapDBToModel };